### ISSUE TITLE
Migrate ecos PR88 to ecos-java-scala

### ISSUE THREAD

**Issue by debasish83** [embotech/ecos-java-scala#1]
I opened up an issue to track the migration. Link to the old PR for reference:

https://github.com/embotech/ecos/pull/88

**Comment by debasish83** [comment]
I am almost done with the refactoring. This license looks good to you right ? Basically ecos is gpl, amd/ldl is lgpl and all code that I will add in java/scala package including examples of spark ecos integration will be Apache. Please correct it as you deem fit.
https://github.com/embotech/ecos-java-scala/blob/master/README.md

**Comment by debasish83** [comment]
If I remember correctly, you wanted com.embotech.ecos as the package name ? I think right now I have com.github.ecos...

**Comment by debasish83** [comment]
@echu @adomahidi please review the code. I am supporting QpSolver and SocpSolver right now and I will update the QpSolver design. I am considering if I should add the Spark-ECOS integration in this repository as well.

**Comment by adomahidi** [comment]
Thanks @debasish83. Will review as soon as possible and get back to you.

**Comment by debasish83** [comment]
I have added the jnilib for MacOSX 64 bit and Linux AMD64...That should pretty much cover most of the dev + prod flows.

**Comment by adomahidi** [comment]
Just ran the examples and they seem to work fine. Thank you very much for the effort and for contributing!
